import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import Projects from "./components/projects";
import Footer from "./shared/footer";
import Navbar from "./shared/navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kevin Herrera - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/assets/icons/pageIco.png
        "
        />
      </Head>
      <Navbar />
      <main className="w-full h-full ">
        <div className=" flex flex-col justify-center items-center  ">
          <div id="home" className=" w-full h-screen pt-40 ">
            <p className=" text-black">home</p>
          </div>
          <div id="about" className=" w-full h-screen   ">
            <p className=" text-black">about</p>
          </div>
          <div id="skills" className=" w-full h-screen    ">
            <p className=" text-black">skills</p>
          </div>
          <Projects />
          <div id="contact" className=" w-full h-screen  ">
            <p className=" text-black">contact</p>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
}
