import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import About from "./components/about";
import Contact from "./components/contact";
import Projects from "./components/projects";
import SideMedia from "./components/sideMedia";
import Skills from "./components/skills";
import Footer from "./shared/footer";
import Navbar from "./shared/navbar";
import Splash from "./shared/splash";

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [windowState, setWindowState] = useState(undefined);
  useEffect(() => {
    console.log(loading);
  }, [loading]);

  useEffect(() => {
    setWindowState(typeof windowState);
    if (typeof windowState !== "undefined") {
      setTimeout(function () {
        setLoading(false);
      }, 2000);
    } else {
      setLoading(true);
    }
  }, [windowState]);

  return (
    <div>
      <Head>
        <title>Kevin Herrera - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="/assets/icons/pageIco.png
        "
        />
      </Head>
      {loading ? (
        <Splash />
      ) : (
        <>
          <Navbar />
          <main className="w-full h-full pt-20">
            <About />
            <Skills />
            <Projects />
            <Contact />
            <SideMedia />
          </main>
          <Footer />
        </>
      )}
    </div>
  );
}

/*

<>
          {" "}
         
        </>
*/
